### PR TITLE
[FEATURE] Added Email Template and Mailing Support for Email Template…

### PR DESCRIPTION
**Pull request by lewisvoncken**
… Configuration

### CODE REVIEW

**Comment by dheesbeen** [comment]
Lets make a snippet out of it! @lewisvoncken

**Comment by lewisvoncken** [comment]
@dheesbeen I will make a snippet out of it but is it possible that it can be merged?

**Comment by krukas** [comment]
@lewisvoncken  I'm with @dheesbeen that this need to be separate. If we want to keep it in the system snippet it should be field type, because now nobody knows this is going to happen if you choise a mail template as source model.

**Comment by lewisvoncken** [comment]
@krukas en @dheesbeen 
Can this please be merged and I will try to make a snippet for it some where in the next few months?

**Comment by krukas** [comment]
@lewisvoncken If you could make an option in the extra kwargs so its more explicit to the user on what is generated. Could be a simple Boolean option (maybe depends on source_model value of the email class)

**Pull request merged**
