### PR TITLE
[TASK] [issue-153] Use DataModels instead of Models for search result…

### PR DESCRIPTION
**Pull request by tuyennn**
…s items in repositories

### Description
Repositories should be returning DataModels instead of Models in their search results. Magento has been slow to move this way, but it would be nice for Mage2Gen to support this ahead of the curve. An example of Magento doing this: https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Customer/Model/ResourceModel/CustomerRepository.php#L373 and https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Customer/Model/Customer.php#L310

### Fixed Issues (if relevant)

**[krukas/Mage2Gen#153](https://github.com/krukas/Mage2Gen/issues/153): Use DataModels instead of Models for search results items in repositories**

+ Implement getDataModel on Model
+ Change applied to getList() on ModelRepository, searchResult items should returns DataModels

### CODE REVIEW

**Comment by dheesbeen** [comment]
@tuyennn Thanks for this great pull request. Can you finish it by creating het separate extensible model in a data folder with the getter and setters and leave the getDataModel within the main model?
Just like within the Magento Customer module?

**Comment by tuyennn** [comment]
Hi @dheesbeen actually on Model there is no implements for getDataModel() function from the interface.

See
https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Customer/Api/Data/CustomerInterface.php

And 
https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Customer/Model/Customer.php

But it's ok, I added the changes

**Comment by dheesbeen** [comment]
@tuyennn This is not exactly what i meant. I want to de separate the data model and the factory model

For example Blog module

Model/Blog (contains the getDataModel)
Model/Data/Blog (extendible data object which implements Api/Blog/Data/Interface

You are welcom to join are slack channel. mage2gen.slack.com.

Thanks again for your contributions!

**Comment by tuyennn** [comment]
> @tuyennn This is not exactly what i meant. I want to de separate the data model and the factory model
> 
> For example Blog module
> 
> Model/Blog (contains the getDataModel)
> Model/Data/Blog (extendible data object which implements Api/Blog/Data/Interface
> 
> You are welcom to join are slack channel. mage2gen.slack.com.
> 
> Thanks again for your contributions!

@dheesbeen How to join your slack channel?

**Pull request closed without merging**
