### PR TITLE
Add missing interface for Extension Attributes

### PR DESCRIPTION
**Pull request by lbajsarowicz**
## Problem

Generated code does not have Interface that refers to:
image

## Solution

`\M2Coach\StoreLocator\Api\Data\StoreExtensionInterface` is generated

### CODE REVIEW

**Comment by thomas-kl1** [comment]
Isn't StoreExtensionInterface generated on the fly by Magento during the di compilation?

**Comment by lbajsarowicz** [comment]
Let me confirm once again, but `setup:di:compile` failed because of that reference.

**Comment by thomas-kl1** [comment]
This class is generated by Magento, based on the items in the extension_attributes.xml pool file. Does StoreInterface extends Magento\Framework\Api\ExtensibleDataInterface ?

**Comment by lbajsarowicz** [comment]
Let me confirm that. But yes, that might be the reason. I'll check that afternoon

**Comment by lbajsarowicz** [comment]
@thomas-kl1 Thank you for verifying that, you are right. I'm not sure why this failed for me during the demo with generated code, however now I generated it and interface was created properly.

Closing.

**Pull request closed without merging**
