### PR TITLE
Add di.xml preferences

### PR DESCRIPTION
**Pull request by VincentMarmiesse**
I hope I didn't do any typo!

### CODE REVIEW

**Comment by VincentMarmiesse** [comment]
The travis error is `PHP Fatal error:  Call to undefined function PHP_CodeSniffer\get_declared_traits() in phar:///home/travis/build/krukas/Mage2Gen/phpcs.phar/autoload.php on line 2`

Is it related to my commit?

**Comment by krukas** [comment]
Hi Vincent,

Thanks for the pull request, i didnt have time to look at the test failures. For the di.xml change, is think we need to move those di.xml changes to the add function where the classes is also created. Because now di.xml is only added when an admin grid is created

**Comment by VincentMarmiesse** [comment]
Hi,
My changes actually are in the `self.add_xml` function.

Maybe I didn't understand your reply?

**Comment by krukas** [comment]
I mean that we need to move the preferences di.xml to the ModelSnippet.add function, it's now in the ModelSnippet.add_adminhtml_grid. Creating an xml multiple times don't matter because the will be merged on creation.

**Comment by VincentMarmiesse** [comment]
Hi @krukas,

I have updated this PR, please let me know if this is what you meant. Travis CI build is still failing (even in my other PRs), but I don't know why.

**Comment by krukas** [comment]
Hi @VincentMarmiesse 

This indeed what i mean, i also removed it from the API function.

For Travis I created an issue #73. I had a quick look and I think that its caused by PHP version that Travis used.

**Pull request merged**
